server:
  port: 8080
spring:
  application:
    #应用名称,可选
    name: reggie_take_out
  #datasource:
  #  druid:
  #    driver-class-name: com.mysql.cj.jdbc.Driver

      #zeroDateTimeBehavior=convertToNull就是把日期转换为null代替异常处理
  #    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  #&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  #    username: root
  #    password: "0214"

  shardingsphere:
    datasource:
      #定义的数据源名称，与下列的名字对应
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.138.100:3306/reggie?characterEncoding=utf-8
        username: root
        password: "1234"
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.138.101:3306/reggie?characterEncoding=utf-8
        username: root
        password: "1234"

    masterslave:
      # 读写分离配置,指定从库负载均衡的策略，即指定查询哪个从库，按照什么顺序查
      load-balance-algorithm-type: round_robin #轮询：按顺序来
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave

      #开启控制台SQL显示，默认false
    props:
      sql:
        show: true

  #允许bean定义覆盖,可以使用多个数据源
  main:
    allow-bean-definition-overriding: true

  redis:
    host: localhost
    port: 6379
    #password:
    database: 0

  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射（高版本mybatisplus可以不用写，默认开启）
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键生成策略
      id-type: ASSIGN_ID

reggie:
  path: D:\reggieImages\